# test:
#   image: node:14
#   stage: test
#   script:
#     - npm ci
#     - npm run test-report
#     - node generateVersionFile.js
#   coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
#   artifacts:
#     reports:
#       coverage_report:
#         coverage_format: cobertura
#         path: coverage/cobertura-coverage.xml
#       junit: test-results.xml
#     paths:
#       - version.json
#   tags:
#     - docker

publish:
  image: node:18
  stage: publish
  script:
    - npm config set @${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set ${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}
    - npm publish
  rules: 
    - if: &tagRegex '$CI_COMMIT_TAG =~ /v\d.*/'
  tags: 
    - docker

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  script:
    - echo "Running release job"
  release:
    tag_name: $CI_COMMIT_TAG
    description: './CHANGELOG.md'
  rules:
    - if: *tagRegex
  tags: 
    - docker

# pages:
#   image: node:14
#   stage: pages
#   script:
#     - npx jsdoc index.js
#     - mkdir -p public/jsdoc
#     - mv out/* public/jsdoc
#   artifacts:
#     paths:
#       - public
#   # rules:
#   #   - if: *tagRegex
#   tags:
#     - docker

stages:
  # - test
  # - pages
  - publish
  - release
